---
title: "Wineyard location map of South Australia"
subtitle: "Wine AU under vine cover cropping trial"
author: "Johanna Pihlblad"
date: "May 20, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r, messages = FALSE}
library(tidyverse)
library(sf)
library(ggrepel)
library(ggspatial)
library(cowplot)
```

# insert map of Australia
```{r}

## load AU borders
AU <- st_read("DATA/borders/Australia_Polygon.shp") %>% 
  filter(!str_detect(name, "Island"))

```

```{r}
## limit the files size by a new bbox
new_bb = c(110, -60, 160, -9.1)
names(new_bb) = c("xmin", "ymin", "xmax", "ymax")
attr(new_bb, "class") = "bbox"
## converst new bbox to polygon
mask <- st_as_sfc(new_bb) %>%
  st_as_sf() %>% 
  st_set_crs(4326)

```

```{r}
## crop AU by mask polygon
AU <- st_join(AU, mask, join = st_within, left = FALSE)

```

```{r}
## make map boundary to indicate on insert
map_bb = c(133, -37, 140, -32.5)
names(map_bb) = c("xmin", "ymin", "xmax", "ymax")
attr(map_bb, "class") = "bbox"

## bounding box to plygon
pol <- st_as_sfc(map_bb) %>% 
  st_set_crs(4326)

```

```{r}
## transform crs of AU and pol to the GDA94/Australian Albers projection
## https://epsg.io/3577 

AU <- AU %>% 
  st_transform(3577) 

pol <- pol %>% 
  st_transform(3577)

```

```{r}
## plot insert map
AU_insert <- AU %>% 
  ggplot()+
  geom_sf(fill = "white", color = "grey30")+
  geom_sf(data = pol, lwd = 1, fill=NA, color = "black")+
  theme_void()+
  xlim(st_bbox(AU)[c(1,3)])+
  ylim(st_bbox(AU)[c(2,4)])

AU_insert

```

# Main map of south Southern Australia 

```{r}
## South Australia borders
SA <- st_read("DATA/borders/Australia_Polygon.shp") %>% 
  filter(name == "South Australia") %>% 
  st_transform(3577) 

```

```{r}
## Vineyard locations
pt <- read_csv("DATA/locations.csv")%>% 
  st_as_sf(coords = c("x","y")) %>% 
  st_set_crs(4326) %>% 
  st_transform(3577)

```

```{r}
# plot SA
SA_map <- SA %>% 
  ggplot()+
  geom_sf(fill = "grey90")+
  geom_sf(data = pt, size = 1)+
  geom_text_repel(data = pt, aes(label = location, geometry = geometry), stat = "sf_coordinates", fontface = "bold", size = 3.5)+
  xlim(st_bbox(pol)[c(1,3)])+
  ylim(st_bbox(pol)[c(2,4)])+
  theme_bw()+
  xlab("")+
  ylab("")+
  annotation_scale(location = "br")

SA_map

```


# Insert AU map in SA map

```{r}
SA_au_insert <-  ggdraw() +
  draw_plot(SA_map) +
  draw_plot(AU_insert, x = 0.1, y = 0.1, width = 0.35, height = 0.35)

SA_au_insert

```

```{r}
## save map
ggsave(plot = SA_au_insert, "Output/SA_au_insert.png")
```

